import React, { useEffect } from 'react';

const Particles = () => {
  useEffect(() => {
    const circles = window.document.querySelectorAll('circle');
    Array.from(circles).forEach((circle, index) => {
      // circle.setAttribute('cy', circle.getAttribute('data-cy') || '0');
      circle.animate(
        [
          {
            transform: 'translateY(0)',
          },
          {
            transform: `translateY(${circle.getAttribute('data-y') || '0'}px)`,
          },
        ],
        {
          duration: 1000 + Math.random() * 1000,
          endDelay: 3000,
          easing: 'ease-in',
          delay: index * 15,
          fill: 'forwards',
        }
      );
    });
  }, []);

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="600"
      height="600"
      viewBox="0 0 600 600"
      version="1.1"
    >
      <g
        id="layers"
        stroke="none"
        strokeWidth="1"
        fill="none"
        fillRule="evenodd"
      >
        <g id="layer1" opacity="1">
          <circle
            id="Oval-4"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="172"
            cy="0"
            data-y="379"
            r="25"
          />
          <circle
            id="Oval-14"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="156.5"
            cy="0"
            data-y="316.5"
            r="22.5"
          />
          <circle
            id="Oval-18"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="288"
            cy="0"
            data-y="159"
            r="15"
          />
          <circle
            id="Oval-9"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="252.5"
            cy="0"
            data-y="158.5"
            r="22.5"
          />
          <circle
            id="Oval-20"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="237"
            cy="0"
            data-y="485"
            r="25"
          />
          <circle
            id="Oval-23"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="171.5"
            cy="0"
            data-y="154.5"
            r="27.5"
          />
          <circle
            id="Oval-15"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="371"
            cy="0"
            data-y="437"
            r="30"
          />
          <circle
            id="Oval-27"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="473"
            cy="0"
            data-y="257"
            r="25"
          />
          <circle
            id="Oval-72"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="406"
            cy="0"
            data-y="374"
            r="5"
          />
          <circle
            id="Oval-31"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="131"
            cy="0"
            data-y="352"
            r="30"
          />
          <circle
            id="Oval-57"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="122"
            cy="0"
            data-y="447"
            r="10"
          />
          <circle
            id="Oval-64"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="177"
            cy="0"
            data-y="333"
            r="5"
          />
          <circle
            id="Oval-77"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="424"
            cy="0"
            data-y="260"
            r="5"
          />
          <circle
            id="Oval-59"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="384"
            cy="0"
            data-y="479"
            r="10"
          />
          <circle
            id="Oval-35"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="452"
            cy="0"
            data-y="301"
            r="25"
          />
          <circle
            id="Oval-67"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="288"
            cy="0"
            data-y="430"
            r="5"
          />
          <circle
            id="Oval-37"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="162"
            cy="0"
            data-y="444"
            r="25"
          />
          <circle
            id="Oval-40"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="289"
            cy="0"
            data-y="468"
            r="30"
          />
          <circle
            id="Oval-62"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="484"
            cy="0"
            data-y="371"
            r="15"
          />
          <circle
            id="Oval-45"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="126"
            cy="0"
            data-y="401"
            r="25"
          />
          <circle
            id="Oval-48"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="409"
            cy="0"
            data-y="145"
            r="25"
          />
          <circle
            id="Oval-51"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="493"
            cy="0"
            data-y="319"
            r="25"
          />
          <circle
            id="Oval-53"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="347"
            cy="0"
            data-y="118"
            r="25"
          />
          <circle
            id="Oval-12"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="437"
            cy="0"
            data-y="270"
            r="15"
          />
          <circle
            id="Oval-3"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="410"
            cy="0"
            data-y="408"
            r="30"
          />
          <circle
            id="Oval-73"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="427"
            cy="0"
            data-y="374"
            r="10"
          />
        </g>
        <g id="layer2" opacity="1">
          <circle
            id="Oval-2"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="245"
            cy="0"
            data-y="446"
            r="30"
          />
          <circle
            id="Oval-6"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="450"
            cy="0"
            data-y="345"
            r="30"
          />
          <circle
            id="Oval-16"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="453"
            cy="0"
            data-y="395"
            r="25"
          />
          <circle
            id="Oval-19"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="195"
            cy="0"
            data-y="207"
            r="15"
          />
          <circle
            id="Oval-10"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="339"
            cy="0"
            data-y="168"
            r="10"
          />
          <circle
            id="Oval-21"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="158"
            cy="0"
            data-y="409"
            r="10"
          />
          <circle
            id="Oval-24"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="282"
            cy="0"
            data-y="126"
            r="25"
          />
          <circle
            id="Oval-26"
            fillOpacity="0.8"
            fill="#CEDE5A"
            cx="366"
            cy="0"
            data-y="165"
            r="25"
          />
          <circle
            id="Oval-80"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="494"
            cy="0"
            data-y="282"
            r="20"
          />
          <circle
            id="Oval-29"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="355"
            cy="0"
            data-y="476"
            r="25"
          />
          <circle
            id="Oval-32"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="255"
            cy="0"
            data-y="97"
            r="10"
          />
          <circle
            id="Oval-58"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="275"
            cy="0"
            data-y="508"
            r="10"
          />
          <circle
            id="Oval-74"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="419"
            cy="0"
            data-y="352"
            r="5"
          />
          <circle
            id="Oval-78"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="192"
            cy="0"
            data-y="227"
            r="5"
          />
          <circle
            id="Oval-33"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="222"
            cy="0"
            data-y="126"
            r="25"
          />
          <circle
            id="Oval-36"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="275"
            cy="0"
            data-y="435"
            r="10"
          />
          <circle
            id="Oval-68"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="340"
            cy="0"
            data-y="425"
            r="5"
          />
          <circle
            id="Oval-38"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="195"
            cy="0"
            data-y="479"
            r="20"
          />
          <circle
            id="Oval-41"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="323"
            cy="0"
            data-y="487"
            r="15"
          />
          <circle
            id="Oval-43"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="110"
            cy="0"
            data-y="299"
            r="25"
          />
          <circle
            id="Oval-46"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="223"
            cy="0"
            data-y="412"
            r="10"
          />
          <circle
            id="Oval-49"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="410"
            cy="0"
            data-y="193"
            r="30"
          />
          <circle
            id="Oval-60"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="110"
            cy="0"
            data-y="240"
            r="25"
          />
          <circle
            id="Oval-54"
            fillOpacity="0.8"
            fill="#D8E57B"
            cx="215"
            cy="0"
            data-y="177"
            r="25"
          />
          <circle
            id="Oval-63"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="123"
            cy="0"
            data-y="200"
            r="15"
          />
          <circle
            id="Oval-65"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="178"
            cy="0"
            data-y="357"
            r="10"
          />
          <circle
            id="Oval-75"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="433"
            cy="0"
            data-y="318"
            r="10"
          />
        </g>
        <g id="layer3" opacity="1">
          <circle
            id="Oval-5"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="324.5"
            cy="0"
            data-y="446.5"
            r="22.5"
          />
          <circle
            id="Oval-7"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="167.5"
            cy="0"
            data-y="238.5"
            r="22.5"
          />
          <circle
            id="Oval-17"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="379"
            cy="0"
            data-y="187"
            r="10"
          />
          <circle
            id="Oval-8"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="431"
            cy="0"
            data-y="233"
            r="25"
          />
          <circle
            id="Oval-11"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="198"
            cy="0"
            data-y="413"
            r="25"
          />
          <circle
            id="Oval-22"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="149"
            cy="0"
            data-y="273"
            r="30"
          />
          <circle
            id="Oval-25"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="377"
            cy="0"
            data-y="117"
            r="10"
          />
          <circle
            id="Oval-81"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="310"
            cy="0"
            data-y="101"
            r="15"
          />
          <circle
            id="Oval-28"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="415"
            cy="0"
            data-y="366"
            r="10"
          />
          <circle
            id="Oval-30"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="202"
            cy="0"
            data-y="446"
            r="15"
          />
          <circle
            id="Oval-56"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="91"
            cy="0"
            data-y="264"
            r="10"
          />
          <circle
            id="Oval-61"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="166"
            cy="0"
            data-y="345"
            r="10"
          />
          <circle
            id="Oval-76"
            fillOpacity="0.8"
            fill="#EF8C52"
            cx="429"
            cy="0"
            data-y="287"
            r="5"
          />
          <circle
            id="Oval-66"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="178"
            cy="0"
            data-y="342"
            r="5"
          />
          <circle
            id="Oval-34"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="464"
            cy="0"
            data-y="210"
            r="25"
          />
          <circle
            id="Oval-70"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="300"
            cy="0"
            data-y="435"
            r="10"
          />
          <circle
            id="Oval-69"
            fillOpacity="0.8"
            fill="#7BCAEC"
            cx="379"
            cy="0"
            data-y="404"
            r="5"
          />
          <circle
            id="Oval-39"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="456"
            cy="0"
            data-y="166"
            r="25"
          />
          <circle
            id="Oval-42"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="452"
            cy="0"
            data-y="431"
            r="15"
          />
          <circle
            id="Oval-44"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="116"
            cy="0"
            data-y="168"
            r="15"
          />
          <circle
            id="Oval-47"
            fillOpacity="0.8"
            fill="#A5CE52"
            cx="321"
            cy="0"
            data-y="149"
            r="25"
          />
          <circle
            id="Oval-50"
            fillOpacity="0.8"
            fill="#EB6F7C"
            cx="503"
            cy="0"
            data-y="233"
            r="10"
          />
          <circle
            id="Oval-52"
            fillOpacity="0.8"
            fill="#8FBBE6"
            cx="419"
            cy="0"
            data-y="459"
            r="30"
          />
          <circle
            id="Oval-55"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="160"
            cy="0"
            data-y="203"
            r="25"
          />
          <circle
            id="Oval-13"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="137"
            cy="0"
            data-y="234"
            r="10"
          />
          <circle
            id="Oval-71"
            fillOpacity="0.8"
            fill="#AE8CBC"
            cx="195"
            cy="0"
            data-y="384"
            r="10"
          />
          <circle
            id="Oval-79"
            fillOpacity="0.8"
            fill="#F7EF4A"
            cx="215"
            cy="0"
            data-y="205"
            r="5"
          />
        </g>
      </g>
    </svg>
  );
};

export default Particles;
